# Generated by Django 4.2.6 on 2024-06-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('secret', models.CharField(max_length=10)),
                ('rateplan', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=250, null=True)),
                ('sex', models.CharField(max_length=6, null=True)),
                ('dob', models.DateField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('checkout_id', models.CharField(max_length=200)),
                ('cart_token', models.CharField(max_length=200)),
                ('checkout_token', models.CharField(max_length=200)),
                ('confirmation_number', models.CharField(max_length=200)),
                ('order_number', models.CharField(max_length=200)),
                ('order_status_url', models.CharField(max_length=250)),
                ('token', models.CharField(max_length=200)),
                ('total_price', models.CharField(max_length=200)),
                ('presentment_currency', models.CharField(max_length=200)),
                ('payment_url', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
