# Generated by Django 4.2.6 on 2024-06-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0003_shopifyorder_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='gateway_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
