# Generated by Django 4.2.6 on 2024-06-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0004_shopifyorder_gateway_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopify',
            old_name='name',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='shopify',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='shopify',
            name='number',
        ),
        migrations.RemoveField(
            model_name='shopify',
            name='rateplan',
        ),
        migrations.RemoveField(
            model_name='shopify',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='shopify',
            name='sex',
        ),
        migrations.AddField(
            model_name='shopify',
            name='api_key',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopify',
            name='shop_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='shopify',
            name='webhook_secret',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
    ]
