# Generated by Django 4.2.6 on 2024-06-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0005_rename_name_shopify_password_remove_shopify_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopify',
            name='name',
            field=models.CharField(default='a', max_length=250),
            preserve_default=False,
        ),
    ]
