# Generated by Django 4.2.6 on 2024-06-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0006_shopify_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='shop_id',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
