# Generated by Django 4.2.6 on 2024-06-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0007_shopifyorder_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopify',
            name='bml_key',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
