# Generated by Django 4.2.6 on 2024-06-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intergration', '0008_shopify_bml_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyorder',
            name='cart_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='checkout_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='checkout_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='gateway_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='order_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='order_status_url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shopifyorder',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
